#!/usr/bin/env bash
#
# MVP 环境初始化脚本
# Generated: 2025-12-03
# Purpose: 一键设置开发/训练环境
#
# Usage:
#   ./scripts/setup_mvp_env.sh [--gpu|--cpu]
#
# Requirements:
#   - Python 3.11+
#   - pip or poetry
#   - (Optional) CUDA 12.1 for GPU support

set -e  # 遇到错误立即退出
set -u  # 使用未定义变量时报错

# === 颜色定义 ===
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# === 辅助函数 ===
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# === 检测操作系统 ===
detect_os() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "macos"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "linux"
    else
        echo "unknown"
    fi
}

# === 检测GPU ===
detect_gpu() {
    if command -v nvidia-smi &> /dev/null; then
        log_info "检测到 NVIDIA GPU:"
        nvidia-smi --query-gpu=name,memory.total --format=csv,noheader
        return 0
    else
        log_warning "未检测到 NVIDIA GPU，将使用 CPU 模式"
        return 1
    fi
}

# === 检查Python版本 ===
check_python() {
    log_info "检查 Python 版本..."
    
    if command -v python3 &> /dev/null; then
        PYTHON_CMD="python3"
    elif command -v python &> /dev/null; then
        PYTHON_CMD="python"
    else
        log_error "未找到 Python！请先安装 Python 3.11+"
        exit 1
    fi
    
    PYTHON_VERSION=$($PYTHON_CMD --version | awk '{print $2}')
    log_success "Python 版本: $PYTHON_VERSION"
    
    # 检查版本是否 >= 3.11
    MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
    MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)
    
    if [[ $MAJOR -lt 3 ]] || [[ $MAJOR -eq 3 && $MINOR -lt 11 ]]; then
        log_error "Python 版本过低！需要 3.11+，当前: $PYTHON_VERSION"
        exit 1
    fi
}

# === 安装依赖 ===
install_dependencies() {
    local MODE=$1  # "gpu" or "cpu"
    
    log_info "开始安装依赖（模式: $MODE）..."
    
    # 检查是否使用Poetry
    if [[ -f "pyproject.toml" ]] && command -v poetry &> /dev/null; then
        log_info "检测到 Poetry，使用 Poetry 安装..."
        
        # 安装依赖
        poetry install
        
        # GPU模式：安装CUDA版PyTorch
        if [[ "$MODE" == "gpu" ]]; then
            log_info "安装 PyTorch (CUDA 12.1)..."
            poetry run pip install torch==2.4.1+cu121 torchvision==0.19.1+cu121 torchaudio==2.4.1+cu121 \
                --index-url https://download.pytorch.org/whl/cu121
        fi
        
        log_success "Poetry 依赖安装完成"
    else
        log_info "使用 pip 安装..."
        
        # 创建虚拟环境（如果不存在）
        if [[ ! -d "venv" ]]; then
            log_info "创建虚拟环境..."
            $PYTHON_CMD -m venv venv
        fi
        
        # 激活虚拟环境
        source venv/bin/activate
        
        # 升级pip
        pip install --upgrade pip
        
        # GPU模式：先安装CUDA版PyTorch
        if [[ "$MODE" == "gpu" ]]; then
            log_info "安装 PyTorch (CUDA 12.1)..."
            pip install torch==2.4.1+cu121 torchvision==0.19.1+cu121 torchaudio==2.4.1+cu121 \
                --index-url https://download.pytorch.org/whl/cu121
        else
            log_info "安装 PyTorch (CPU)..."
            pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1
        fi
        
        # 安装其他依赖
        log_info "安装其他依赖..."
        pip install -r requirements.txt
        
        log_success "pip 依赖安装完成"
    fi
}

# === 创建必要目录 ===
create_directories() {
    log_info "创建必要目录..."
    
    mkdir -p data/synthetic
    mkdir -p data/bdd100k
    mkdir -p data/cityscapes
    mkdir -p data/cache
    
    mkdir -p artifacts/checkpoints
    mkdir -p artifacts/pseudo_labels
    
    mkdir -p reports
    mkdir -p logs
    
    log_success "目录创建完成"
}

# === 设置环境变量 ===
setup_env_vars() {
    log_info "设置环境变量..."
    
    # 创建.env文件（如果不存在）
    if [[ ! -f ".env" ]]; then
        cat > .env <<EOF
# MVP 环境变量
# Generated by setup_mvp_env.sh

# 数据路径
DATA_ROOT=data
ARTIFACT_ROOT=artifacts

# Prometheus监控
PROMETHEUS_PORT=8000

# CUDA设置（GPU模式）
CUDA_VISIBLE_DEVICES=0

# PyTorch设置
OMP_NUM_THREADS=4
MKL_NUM_THREADS=4

# 日志级别
LOG_LEVEL=INFO

# Weights & Biases（可选）
# WANDB_API_KEY=your_api_key_here
# WANDB_PROJECT=traffic-rules-mvp
EOF
        log_success ".env 文件已创建"
    else
        log_warning ".env 文件已存在，跳过"
    fi
}

# === 验证安装 ===
verify_installation() {
    log_info "验证安装..."
    
    # 检查PyTorch
    log_info "检查 PyTorch 安装..."
    $PYTHON_CMD -c "import torch; print(f'PyTorch version: {torch.__version__}')"
    $PYTHON_CMD -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}')"
    if $PYTHON_CMD -c "import torch; exit(0 if torch.cuda.is_available() else 1)" 2>/dev/null; then
        $PYTHON_CMD -c "import torch; print(f'CUDA version: {torch.version.cuda}')"
        $PYTHON_CMD -c "import torch; print(f'GPU count: {torch.cuda.device_count()}')"
    fi
    
    # 检查其他关键包
    log_info "检查其他依赖..."
    $PYTHON_CMD -c "import pydantic; print(f'Pydantic: {pydantic.__version__}')" || log_warning "Pydantic 未安装"
    $PYTHON_CMD -c "import yaml; print('PyYAML: OK')" || log_warning "PyYAML 未安装"
    $PYTHON_CMD -c "import cv2; print(f'OpenCV: {cv2.__version__}')" || log_warning "OpenCV 未安装"
    
    log_success "验证完成"
}

# === 运行示例测试 ===
run_example_tests() {
    log_info "运行示例测试..."
    
    # 测试规则引擎
    log_info "测试规则引擎（梯度验证）..."
    if $PYTHON_CMD -m src.traffic_rules.rules.red_light; then
        log_success "规则引擎测试通过"
    else
        log_warning "规则引擎测试失败（可能缺少依赖）"
    fi
    
    # 测试约束损失
    log_info "测试约束损失函数..."
    if $PYTHON_CMD -m src.traffic_rules.loss.constraint; then
        log_success "约束损失测试通过"
    else
        log_warning "约束损失测试失败（可能缺少依赖）"
    fi
}

# === 主函数 ===
main() {
    echo ""
    echo "╔════════════════════════════════════════════════════════╗"
    echo "║   Traffic Rules MVP - 环境初始化脚本                  ║"
    echo "║   Version: 1.0                                        ║"
    echo "║   Date: 2025-12-03                                    ║"
    echo "╚════════════════════════════════════════════════════════╝"
    echo ""
    
    # 解析参数
    MODE="auto"
    if [[ $# -gt 0 ]]; then
        case "$1" in
            --gpu)
                MODE="gpu"
                ;;
            --cpu)
                MODE="cpu"
                ;;
            --help)
                echo "Usage: $0 [--gpu|--cpu]"
                echo ""
                echo "Options:"
                echo "  --gpu    强制使用GPU模式（安装CUDA版PyTorch）"
                echo "  --cpu    强制使用CPU模式"
                echo "  --help   显示帮助信息"
                exit 0
                ;;
            *)
                log_error "未知参数: $1"
                echo "使用 --help 查看帮助"
                exit 1
                ;;
        esac
    fi
    
    # 自动检测模式
    if [[ "$MODE" == "auto" ]]; then
        OS=$(detect_os)
        log_info "检测到操作系统: $OS"
        
        if [[ "$OS" == "macos" ]]; then
            log_info "macOS 系统，使用 CPU 模式"
            MODE="cpu"
        elif detect_gpu; then
            MODE="gpu"
        else
            MODE="cpu"
        fi
    fi
    
    log_info "安装模式: $MODE"
    
    # 执行安装步骤
    check_python
    create_directories
    install_dependencies "$MODE"
    setup_env_vars
    verify_installation
    
    # 可选：运行测试
    echo ""
    read -p "是否运行示例测试？(y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        run_example_tests
    fi
    
    # 完成
    echo ""
    log_success "════════════════════════════════════════════════════════"
    log_success "  环境初始化完成！"
    log_success "════════════════════════════════════════════════════════"
    echo ""
    log_info "下一步操作："
    echo "  1. 激活环境:"
    if [[ -d "venv" ]]; then
        echo "     source venv/bin/activate"
    else
        echo "     poetry shell"
    fi
    echo "  2. 生成合成数据:"
    echo "     python scripts/prepare_synthetic_data.py"
    echo "  3. 运行训练:"
    echo "     python tools/train_red_light.py run --config configs/mvp.yaml"
    echo "  4. 运行测试:"
    echo "     python tools/test_red_light.py run --scenario all"
    echo ""
    log_info "查看文档: docs/development/Development-ITER-2025-01.md"
    echo ""
}

# 执行主函数
main "$@"
